### ISSUE TITLE
Add open command

### ISSUE THREAD

**Issue by todrobbins** [brechtcs/dterm#6]
Not sure where to start, but I'd love to have the `open` command, similar to that in Finder (macOS) where I can say `open .` to open the current directory in Finder, but instead it would open a new tab in Beaker.

Thoughts?

**Comment by brechtcs** [comment]
Agreed. I'm currently running some final tests before releasing [v0.2](https://github.com/dterm/dterm/pull/5), and I'll tackle this after that's done.

**Comment by brechtcs** [comment]
I decided to already add a [very basic](https://github.com/dterm/dterm/pull/5/commits/31c1f5a7dd934f83ee27f47b6de81d4df1833cfc) implementation into the 0.2 branch. Should be able to release it later this week.

**Comment by brechtcs** [comment]
[Released!](https://github.com/dfurl/dterm/releases/tag/v0.2.0)

Let me know if you have any problems updating. Everything should be backwards compatible, except the configuration, for which I've added the `term recover` command mentioned in the release notes.

(If the `open` command is not available straight away, you might have to run `term install dat://dterm.hashbase.io/commands/open.js` to make it work.)

**Comment by todrobbins** [comment]
Thanks @brechtcs! Works like a charm!
